appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: twLqErgkFy79/K/aELRab7UynzOL0aOJmlgNNQjn711Cdw/Zg0Q5bpP+gqeigE6xFubWDR7n71M32kcVpzpwV7CRkeLEmVio23buFxS9Psb55TL/hyFMcpgO+c/H8OMqwDI6Xj9Lr/+VqKk5mfIA6rzHrbegOBS1W0bji0TqgYvuaTQRdL+RcZOzO9Dzybm/xM/FhIAbYcdo9WiLHQtRYklNnVgTsUfbFjipmRxGQUb6yRh6q3Kb0Y5p1ZgqlvhctkVFXEc+t7tm8KaASn3y0PPbOm69lMTSeDpW4pcLKs+fQvq/9c1Ku8A0RhFjEUEcL7vsNZh12xqMkiQRbRFTAzCLXWvsysaP9gLlcPdLZo5gahJgHnCDsK5BljAXm3Oqi1CamGmcsuqbCGlRgMyu5x0jHAs6alGgV574HpMuwTsykhVB8Rxmp65rJWdXNunUsK15jJTfXiGPHrPDItJNP0Obc5cBQY65zC0gYfV46ehhCVG1CHMtoe3V1mDwckmNIs9uV4XfJ8Er622WwHdYlS+Ayqxu1i67IHXRFsw3fQeNQbbWe1CHotv+aaj5BQ+ijS3fM+XzBVKNbewE9A7Au4jyxTj764jFft7KT0FKCfT82AD8uCLggzHA/SyzfVT2D+YsVeZxpwdgCZf36o9rTJDNhZRL+06mwxDIY0lMS5o=}
