travis:
  secure:
    BINSTAR_TOKEN: gxVzAzvByyI8xSLofMWSRrmgLKUY/W9HXrLSA3RTg2/SKgYpXTzPo9vyupBOGpWOhVwdYMKAdpoAgkuXwxQkGakOcjTNi1G2iG+IaMk8q+o5aqK+zZgloIa59HTJLzROzBqWZjhAfs9WsdvC2XrVhF6Wh/0FIBe7SHuNecsjB/R9zq4bVMcCFB4MEKIgQcnpHBtM7xbz6c5oD/AlRVm4Q2HvV67QOKLXmGNptxtMdvIBIfbz17jR1fcXnHbFMwvVp0TKYzE8kGGullv0FGmmB4Wj6t2ejbKJ2C8yf1sewDk9Npz143ry8vAlXis+myARuh2abjHDbkTLU6vrg+kU+W3lZb4695SjN9J3kZKfxEBPr0I0dmQfFFS6vpU/hFTt0AhDb3M18NE3EIX7EBjpIDPv2pRMlFh5QJFFm0FU2GuplC0KmIizE9LIJQiDZ8Jm1HJadeEWznYacS4oG4WJShN/bM0koaUhktjpmeCG7SCu7rtpbHmENaZ+hlmKaCPOlB2RR5rIIrdH7p3SoQQdc3RX/TOHZ2rapXH+/mrdNe42Skco28rPIXGWNVWhwkfstRhF8B+vXnHyk1hZIZHlXK+qcrt5ty5Kx0zcnUfiNpawnGiVaLijWm4Xn28Zv8GMj0ONkI7D9lMdf1PG7uyOm05J7HIsiKDh7xKtV0hSR60=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
